export const CHANGE_THEME_OBJECT = 'reducer/change theme object'
export const CHANGE_THEME_VALUE = 'reducer/change theme value'
export const ADD_ITEM_TO_HISTORY = 'reducer/add item to history'
export const CHANGE_DISPLAY_VALUE = 'reducer/change display value'
export const SET_OWN_VALUE = 'reducer/set own value'
export const SET_DEFAULT_VALUE = 'reducer/set default value'
export const CLEAR_ALL_DATA = 'reducer/clear all data'
